# GeminiCraftChat 配置文件

# 调试模式
debug: false

# API 设置
api:
  # API密钥 (也可以通过环境变量 GEMINI_API_KEY 设置)
  key: "your-api-key-here"
  # 使用的模型
  model: "gemini-pro"
  # 代理设置
  proxy:
    enabled: false
    host: "127.0.0.1"
    port: 7890

# 聊天设置
chat:
  # 触发词设置
  trigger: "ai"
  trigger_words:
    - "ai"
    - "@ai"
    - "!ai"
  # 消息格式
  format:
    thinking: "§7[AI] §f正在思考中..."
    response: "§7[AI] §f%s"
    error: "§c[AI] 发生错误：%s"
  # 冷却时间 (毫秒)
  cooldown: 10000
  # 历史记录长度限制
  max_history: 10

# 人设配置
personas:
  default:
    name: "默认助手"
    description: "一个友好的AI助手"
    context: "你是一个友好的AI助手，会用简短的语言回答问题。"
  minecraft:
    name: "MC专家"
    description: "Minecraft游戏专家"
    context: "你是一个Minecraft游戏专家，精通红石、建筑和游戏机制，会用简短的语言回答问题。"
  rpg:
    name: "RPG角色"
    description: "角色扮演游戏中的NPC"
    context: "你是一个生活在中世纪魔法世界的NPC，说话时要符合角色设定，用简短的语言回答问题。"

# 敏感词过滤
filter:
  enabled: true
  words:
    - "敏感词1"
    - "敏感词2"
  replacement: "***"

# 命令设置
commands:
  # 中文命令
  chinese:
    clear_memory: ["清除记忆", "清空记忆", "忘记对话"]
    switch_persona: ["切换人设", "换个角色", "更换人设"]
    list_personas: ["查看人设", "人设列表", "所有角色"]
    help: ["帮助", "指令", "命令"] 